### PR TITLE
'js/integram-table.js Я пытаюсь отредактировать роль  кнопкой .edit-icon и получаю ошибку'

### LINKED ISSUE #921: js/integram-table.js Я пытаюсь отредактировать роль  кнопкой .edit-icon и получаю ошибку
Ошибка:
installHook.js:1 Error opening edit form: Error: Record 557 not found
    at IntegramTable.fetchRecordData (integram-table.js:7181:23)
    at async IntegramTable.openEditForm (integram-table.js:6909:34)

Из-за запроса 
https://ideav.ru/ru2/object/42/?JSON_OBJ&FR_42=@557

Потому что 557 - это id пользователя, в ячейке которого я хочу отредактировать роль, а у самой роли id 520.

Ошибка появилась после https://github.com/ideav/crm/pull/916 и теперь берется неверный id.

### PR DESCRIPTION
**Pull request by konard**
## Summary

Fixes #921 — regression introduced by PR #916.

- After PR #916, clicking the `.edit-icon` on a reference field cell (e.g. "role" in a user row) that had just been filled for the first time threw `Error: Record 557 not found` — where 557 was the **user's** row ID, not the role's ID (520).
- Root cause: `updateCellDisplay()` reconstructed the edit icon using `cell.dataset.recordId` (the parent row's ID = 557) instead of the reference record's own ID (= 520).

## Root Cause

PR #916 added code in `updateCellDisplay()` to construct a new `.edit-icon` when a previously empty cell gets its first value. It used `cell.dataset.recordId` as the `recordId` argument to `openEditForm`. However, `data-record-id` stores the **parent row's** record ID (e.g. the user's ID 557), while for reference fields the edit icon must use the **referenced record's** ID (e.g. the role's ID 520).

In `renderCell()`, the existing edit icon is correctly built using `refValueId` (the parsed reference ID from `"id:Value"` format). But `data-ref-value-id` was only set during initial render and never updated after an inline edit save.

## Fix

Two changes in `js/integram-table.js`:

1. **`saveReferenceEdit()`**: After a successful save, set `cell.dataset.refValueId = selectedId` — this ensures the `data-ref-value-id` attribute reflects the newly selected reference record ID.

2. **`updateCellDisplay()`**: When constructing the edit icon, use `cell.dataset.refValueId || cell.dataset.recordId` as the record ID — for reference fields this picks the reference's own ID; for non-reference fields it falls back to the row's record ID as before.

## Test plan

- [ ] Fill in an empty reference cell (e.g. role in a user row) using inline editing — verify the pencil edit icon appears immediately and clicking it opens the correct record (not the parent row's record)
- [ ] Verify existing non-empty reference cells still show the edit icon and open the correct record
- [ ] Verify non-reference cells (text, date, etc.) that go from empty to filled still show the edit icon correctly
- [ ] Verify multi-select reference fields still do NOT show an edit icon

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by konard** [comment]
## 🤖 Solution Draft Log
This log file contains the complete execution trace of the AI solution draft process.

💰 **Cost estimation:**
- Public pricing estimate: $0.062783
- Calculated by Anthropic: $0.622296 USD
- Difference: $0.559513 (+891.19%)
📎 **Log file uploaded as Gist** (579KB)
🔗 [View complete solution draft log](https://gist.githubusercontent.com/konard/f69ad485ee4388aeeaee5030a51b5858/raw/eaf5ab75678093d86e290aa834a6244d20062148/solution-draft-log-pr-1773488967387.txt)
---
*Now working session is ended, feel free to review and add any feedback on the solution draft.*
